# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vip-chat-native-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vip-chat-native-ios

  target 'vip-chat-native-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'vip-chat-native-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
